name: flutter_ty_mobile
description: New version of TY mobile app for multi platforms.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.5.3+2

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  meta: ^1.1.8
  json_annotation: ^3.0.1

  # Service Locators (Object Injectors) https://pub.dev/packages/get_it
  get_it: ^4.0.2
  # Widget State Management (Object Provider) https://pub.dev/packages/provider
#  provider: ^4.0.1
  # Bloc for State Management https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^4.0.1
  # MobX https://pub.dev/packages/mobx
  mobx: ^1.2.1
  flutter_mobx: ^1.1.0
  # Rx Api  https://pub.dev/packages/rxdart
  rxdart: ^0.24.1
  # Navigator https://pub.dev/packages/auto_route
  auto_route: ^0.5.0
  # Device Orientation https://pub.dev/packages/orientation
  orientation: ^1.2.0
  # Sensor Plugin https://pub.dev/packages/aeyrium_sensor
#  aeyrium_sensor: ^1.0.7
  # After Layout https://pub.dev/packages/after_layout
  after_layout: ^1.0.7+2
  # Functional programming thingies https://pub.dev/packages/dartz
  dartz: ^0.9.1
  # Freezed (Data class with Json factory, Combine: super_enum, equatable, to_string,...) https://pub.dev/packages/freezed
  freezed_annotation: ^0.11.0
  # Simpler Data class(equatable, to_string, copyWith, hash) https://pub.dev/packages/dataclass
  dataclass: ^0.3.0+1
  # Generic Enum https://pub.dev/packages/generic_enum
  generic_enum: ^0.2.3
  generic_enum_annotation: ^0.1.7
  # Super Enum (Data class like Enum) https://pub.dev/packages/super_enum
  super_enum: ^0.4.2
  # Value equality https://pub.dev/packages/equatable
#  equatable: ^1.2.0
  # Dart class to String https://pub.dev/packages/to_string
#  to_string: ^1.2.1
  # Email Validate https://pub.dev/packages/email_validator
  email_validator: ^1.0.4
  # Datetime format
  intl: ^0.16.1
  # Debug Logger https://pub.dev/packages/logger
  logging: ^0.11.4
  # HTTP Request - Dio https://pub.dev/packages/dio
  dio: ^3.0.9
  dio_flutter_transformer: ^3.0.2
  # Cookie Manager https://pub.dev/packages/dio_cookie_manager
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.1
  # HTTP Logger https://pub.dev/packages/pretty_dio_logger
  pretty_dio_logger: ^1.1.1
  # Network state
  connectivity: ^0.4.8+6
  data_connection_checker: ^0.3.4
  # Hive (noSQL) https://pub.dev/packages/hive
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  # Get commonly used locations on the filesystem. Supports iOS and Android.
  # https://pub.dev/packages/path_provider
  path_provider: ^1.6.10
  # Handle device permission https://pub.dev/packages/permission_handler
  permission_handler: ^5.0.1
  # Custom Permission Dialog https://pub.dev/packages/easy_permission_validato
  easy_permission_validator: ^2.0.0
  # Screen Util for adapting screen and font size https://pub.dev/packages/flutter_screenutil
#  flutter_screenutil: ^1.1.0
  # Official image extension https://pub.dev/packages/extended_image
  extended_image: ^0.9.0
  # Official icons https://pub.dev/packages/cupertino_icons
  # Use with the CupertinoIcons class for iOS style icons.
#  cupertino_icons: ^0.1.3
  # Multi useful widgets https://pub.dev/packages/flui
  # Docs: https://www.flui.xin/en/guide.html
  flui: ^0.9.2
  # Stylish SnackBar https://pub.dev/packages/flushbar
  # 2020/02/17 - flutter upgrade crashes this, need to wait for package update
#  flushbar: ^1.9.1
  # Font Awesome from https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: ^8.8.1
  # Advance Photo Viewer https://pub.dev/packages/carousel_pro
  carousel_pro: ^1.0.0
  # Relative Align Widget https://pub.dev/packages/relative_layout
  relative_layout: ^0.1.0+1
  # WebView https://pub.dev/packages/webview_flutter
  webview_flutter: ^0.3.22+1
  # HTML as Text https://pub.dev/packages/flutter_html:
  flutter_html: ^1.0.0
  # Launch Url https://pub.dev/packages/url_launcher
  url_launcher: ^5.4.10
  # QR Code generator https://pub.dev/packages/qr_flutter
  qr_flutter: ^3.2.0
  # Configurable Expansion List Tile https://pub.dev/packages/configurable_expansion_tile
  configurable_expansion_tile: ^1.0.0
  # Share Function https://pub.dev/packages/share_extend
  share_extend: ^1.1.7
  # Icon Badge https://pub.dev/packages/badges
  badges: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  source_gen:
  build_runner:
  json_serializable: ^3.3.0
  hive_generator: ^0.7.0+2
  mobx_codegen: ^1.1.0
  mockito: ^4.1.1
  bloc_test: ^5.1.0
  flutter_vector_icons: ^0.2.1
  auto_route_generator: ^0.5.0
  freezed: ^0.11.0
  dataclass_generator: ^0.3.0+2
  generic_enum_builder: ^0.2.3
#  to_string_generator: ^1.2.1
  super_enum_generator: ^0.5.0

dependency_overrides:
  dartx: ^0.4.1
  path: ^1.7.0
  build: ^1.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

targets:
  $default:
    builders:
      # Configure the builder `pkg_name|builder_name`
      generic_enum_builder|map_builder:
        # Only run this builder on the specified input.
        enabled: true
        generate_for:
          - lib/*.dart
      # Configure the builder `pkg_name|builder_name`
      generic_enum_builder|json_builder:
        # Only run this builder on the specified input.
        enabled: false
        generate_for:
          - lib/*.dart

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/images/vip/
    - config/app_config.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  # FontAwesome https://fontawesome.com/
  # Example: Icon(IconData(0xf834, fontFamily: 'FontAwesome'))
  fonts:
    - family: FontAwesome
      fonts:
        - asset: assets/fonts/fontawesome_webfont.ttf
          weight: 400

# Flutter localization tool
flutter_intl:
  enabled: true
